- hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: true
      
    - name: Install zip and vim
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - zip
        - vim
